/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aonyi.torneo.ui;

import com.aonyi.torneo.utils.Sexo;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author faguirre
 */
public class FrmNuevoAspirante extends javax.swing.JDialog {

    /**
     * Indica si el usuario presionó la opción "Cancelar"
     */
    String[] retorno = null; 
    
    /**
     * Creates new form FrmNuevoAspirante
     * @param padre Ventana padre (llamadora)
     * @param modal true si es ventana modal
     */
    public FrmNuevoAspirante(JFrame padre, boolean modal) {
        super(padre,modal);
        initComponents();  
    }
    
    /**
     *
     * @return
     */
    public String[] getRetorno() {
        return this.retorno;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblApellido = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblFchNacimiento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        rdbFemenino = new javax.swing.JRadioButton();
        rdbMasculino = new javax.swing.JRadioButton();
        lblDni = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMensajes = new javax.swing.JLabel();
        txtFchNacimiento = new javax.swing.JFormattedTextField();
        txtDni = new javax.swing.JFormattedTextField();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        btnAceptar.setText("Aceptar");
        btnAceptar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblApellido.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 20);
        pnlDatos.add(lblApellido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 30);
        pnlDatos.add(txtNombres, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 30);
        pnlDatos.add(txtApellido, gridBagConstraints);

        lblDireccion.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 20);
        pnlDatos.add(lblDireccion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 30);
        pnlDatos.add(txtDireccion, gridBagConstraints);

        lblFchNacimiento.setText("Fecha de Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 20);
        pnlDatos.add(lblFchNacimiento, gridBagConstraints);

        lblSexo.setText("Sexo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 20);
        pnlDatos.add(lblSexo, gridBagConstraints);

        buttonGroup1.add(rdbFemenino);
        rdbFemenino.setSelected(true);
        rdbFemenino.setText("Femenino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlDatos.add(rdbFemenino, gridBagConstraints);

        buttonGroup1.add(rdbMasculino);
        rdbMasculino.setText("Masculino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlDatos.add(rdbMasculino, gridBagConstraints);

        lblDni.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 20);
        pnlDatos.add(lblDni, gridBagConstraints);

        lblNombres.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 20);
        pnlDatos.add(lblNombres, gridBagConstraints);

        jLabel1.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        pnlDatos.add(jLabel1, gridBagConstraints);

        lblMensajes.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblMensajes.setForeground(new java.awt.Color(0, 0, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 30);
        pnlDatos.add(lblMensajes, gridBagConstraints);
        lblMensajes.getAccessibleContext().setAccessibleName("lblMensajes");

        txtFchNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFchNacimiento.setToolTipText("Fecha  en formato dd/mm/aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 30);
        pnlDatos.add(txtFchNacimiento, gridBagConstraints);

        txtDni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtDni.setToolTipText("Sólo números sin puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 30);
        pnlDatos.add(txtDni, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (this.isCamposCompletos()){
            this.retorno = new String[]{
                    this.txtNombres.getText(),
                    this.txtApellido.getText(),
                    this.txtDireccion.getText(),
                    this.txtFchNacimiento.getText(),
                    (this.rdbMasculino.isSelected())?Sexo.MASCULINO:Sexo.FEMENINO,
                    this.txtDni.getText()};        
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.retorno = null;
        this.setVisible(false);  
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Verifica que todos los campos obligatorios tengan un valor.
     * Devuelve true si están completos
     * @return Todos los campos completos
     */
    private boolean isCamposCompletos(){
        
        /** Resalta las cajas de texto que se encuentran vacías */
        this.txtNombres.setBackground(("".equals(this.txtNombres.getText()))?Color.yellow:Color.white);
        this.txtApellido.setBackground(("".equals(this.txtApellido.getText()))?Color.yellow:Color.white);
        this.txtDireccion.setBackground(("".equals(this.txtDireccion.getText()))?Color.yellow:Color.white);
        this.txtFchNacimiento.setBackground(("".equals(this.txtFchNacimiento.getText()))?Color.yellow:Color.white);
        this.txtDni.setBackground(("".equals(this.txtDni.getText()))?Color.yellow:Color.white);
        
        // Si alguno de los campos está vacío setea retorno en falso
        boolean retorno = ( !"".equals(this.txtNombres.getText()) && 
                            !"".equals(this.txtApellido.getText()) && 
                            !"".equals(this.txtDireccion.getText()) && 
                            !"".equals(this.txtFchNacimiento.getText()) && 
                            !"".equals(this.txtDni.getText()));          
        return retorno;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFchNacimiento;
    private javax.swing.JLabel lblMensajes;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtDni;
    private javax.swing.JFormattedTextField txtFchNacimiento;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

   
}
